version: "2"
run:
  timeout: 5m
  modules-download-mode: readonly
  go: "1.24"

linters:
  enable:
    #- revive
    - goconst
    #- unparam
    - staticcheck
    - unused
  settings:
    goconst:
      min-len: 3
      min-occurrences: 3
    staticcheck:
      checks:
        - all
        - "-SA6002"
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - goconst
          - mnd
